### ISSUE TITLE
Action does not work if flags are empty

### ISSUE THREAD

**Issue by DefCon-007** [grafana/run-k6-action#14]
If no `flags` are set, the action fails with error code 255. 

Steps to reproduce: 
- Trying running the action without any custom flag 
```yaml
      - name: Run k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./k6/foundations/01.basic.js
          flags: --duration 5s
```

The reason seems to be an extra empty space before the path in case the flags are empty.
