### ISSUE TITLE
--block-hostnames flag not parsing correctly

### ISSUE THREAD

**Issue by cjsaurusrex** [grafana/run-k6-action#42]
When using the `--block-hostnames` flag within the `flags` input, the urls are not being individually evaluated and are instead always failing validation with `invalid hostname pattern 'www.example.com,www.k6.io'`. A single url works as expected.

The format I'm providing them in matches the [documentation](https://grafana.com/docs/k6/latest/using-k6/k6-options/reference/#block-hostnames).

If I run the same command locally(which the action outputs before triggering a run), the validation passes and it runs successfully. - `k6 run --block-hostnames="www.example.com,www.k6.io" ./tests/script.js`

Both the GHA and my local machine are using k6 0.5.7.

# Example Workflow
```yaml
on:
  workflow_dispatch:

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: "./tests/script.js"
          flags: --block-hostnames="www.example.com,www.k6.io"
```
