### ISSUE TITLE
Whitespace within flags aren't parsed correctly

### ISSUE THREAD

**Issue by rpdids** [grafana/run-k6-action#44]
When using any flag that contains whitespace (i.e. `--env TEST="Hello World"` or `--user-agent "Hello/World (Hello; World)" results in an error, similar to the below (number of args changes depending on the number of whitespaces in the flag). This is contrary to the CLI behaviour when running locally which accepts the whitespace as expected. Both local and GHA uses k6 version 0.57.0.

`level=error msg="accepts 1 arg(s), received 3: arg should either be \"-\", if reading script from stdin, or a path to a script file"`

### Sample Workflow
```yaml
on:
  workflow_dispatch:

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: "./tests/script.js"
          flags: --user-agent "Hello/World (Hello; World)"
```

After investigating, it appears that the issue is in the [k6helper.ts executeRunK6Command function](https://github.com/grafana/run-k6-action/blob/c6b79182b9b666aa4f630f4a6be9158ead62536e/src/k6helper.ts#L173) where a simple whitespace split is done to parse the flags. 

```js
const parts = command.split(' ')    <------
const cmd = parts[0]
const args = parts.slice(1)
```

As a result, the `parts` array can contain garbled command arguments when whitespace is present (using the UA from above results in `[..., "Hello/World, (Hello;, World)", ...]` ). This array, passed to the ChildProcess spawn function `args`, is invalid as it expects the args array to be single atomic elements and thus providing more arguments as expected.
