### ISSUE TITLE
Environment variables not available in init phase (setting options)

### ISSUE THREAD

**Issue by stalbot15** [grafana/run-k6-action#49]
I'm attempting to pass in environment variables to some scenario options, which works using the CLI, but not when using the action.

## Versions

- CLI version: `k6 v0.56.0 (go1.23.4, darwin/arm64)`
- Setup action: `grafana/setup-k6-action@v1`
- Run action: `grafana/run-k6-action@v1`

## Example of issue

Using the following test which references the `__ENV` object in the init/options phase:
```js
import http from 'k6/http';

export const options = {
  scenarios: {
    test_1: {
      executor: 'constant-arrival-rate',
      duration: __ENV.DURATION,
      preAllocatedVus: 5,
      maxVus: 100,
      rate: __ENV.RATE,
      timeUnit: '1s',
    },
  },
};

export default function () {
  http.get('https://google.com');
}
```

### CLI Example - working 🟢 

I can use the CLI to run the test successfully, either passing in `-e` flags or setting them as system env vars since `--include-system-env-vars` is set to `true` by default:

```sh
k6 run loadTests/example.js -e RATE=1 -e DURATION=10s
```

```sh
RATE=1 DURATION=10s k6 run loadTests/example.js
```

### Actions example - not working 🔴 
Trying the same thing in actions results in a failure, due to the rate/duration not being specified (`__ENV` is null):

```yml
name: k6 test
on:
  workflow_dispatch:
jobs:
  deploy_k6:
    name: Deploy - k6
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: action_setup_k6
        name: action setup k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: 0.56.0
      - id: action_run_k6
        name: action run k6
        uses: grafana/run-k6-action@v1
        with:
          path: ./loadTests/example.js
          debug: true
          flags: -e RATE=5 -e DURATION=10s
          inspect-flags: ""
          parallel: false
          fail-fast: false
          only-verify-scripts: false
        env:
          DURATION: 10s
          RATE: 5
```

Log output:
```
🔍 Validating test run files.
time="2025-05-01T00:09:24Z" level=error msg="There were problems with the specified script configuration:\n\t- scenario test_1 has configuration errors: the iteration rate isn't specified, the duration is unspecified"
Error: No valid test files found
```
